"""Stable, serializable domain identifiers."""

from enum import StrEnum


class Pack(StrEnum):
    PROSPERITY = "PROSPERITY"
    PROMOTION = "PROMOTION"
    LUCK = "LUCK"
    PIRATE = "PIRATE"


class BuildingType(StrEnum):
    SMALL_WALLET = "SMALL_WALLET"
    WISHING_WELL = "WISHING_WELL"
    MONEY_TREE = "MONEY_TREE"
    LUCKY_COLOR_GATE = "LUCKY_COLOR_GATE"
    HALL_OF_WEALTH = "HALL_OF_WEALTH"
    RABBIT_INN = "RABBIT_INN"
    PIGGY_BANK = "PIGGY_BANK"
    PIGLET_BANK = "PIGLET_BANK"
    SMALL_BOOKSTORE = "SMALL_BOOKSTORE"
    BECKONING_CAT_VAULT = "BECKONING_CAT_VAULT"
    FOX_ANTIQUE_SHOP = "FOX_ANTIQUE_SHOP"
    DICE_SCULPTURE = "DICE_SCULPTURE"
    FOUR_LEAF_INN = "FOUR_LEAF_INN"
    LUCKY_STAR_COIN_POND = "LUCKY_STAR_COIN_POND"
    DICE_TOWER = "DICE_TOWER"
    HOLOGRAM_EXPERIENCE_HUT = "HOLOGRAM_EXPERIENCE_HUT"
    TREASURE = "TREASURE"
    SAIL = "SAIL"
    RUDDER = "RUDDER"
    ANCHOR = "ANCHOR"
    CANNON = "CANNON"
    CAPTAIN_HAT = "CAPTAIN_HAT"


class StandType(StrEnum):
    MIMI = "MIMI"
    RABBIT = "RABBIT"
    RACCOON = "RACCOON"
    UPDATE = "UPDATE"
    PIG = "PIG"
    PALUNAN = "PALUNAN"
    JASMINE = "JASMINE"
    FRIED_SHRIMP = "FRIED_SHRIMP"
    THREE_LEAF = "THREE_LEAF"
    PIRATE_KING = "PIRATE_KING"
    GREAT_SHARK = "GREAT_SHARK"
    SHOVEL = "SHOVEL"
    SMALL_SHARK = "SMALL_SHARK"
    BIG_BAG = "BIG_BAG"
    ROLLER = "ROLLER"
    SECRET_BOOK = "SECRET_BOOK"
    CREDIT_CARD = "CREDIT_CARD"


class EventType(StrEnum):
    MOVE_STEP = "MOVE_STEP"
    ADVANCE_STAGE = "ADVANCE_STAGE"
    ACTIVATE_BUILDING = "ACTIVATE_BUILDING"
    ACTIVATE_STAND = "ACTIVATE_STAND"
    TURN_START = "TURN_START"
    MANAGEMENT_START = "MANAGEMENT_START"
    BUY_BUILDING = "BUY_BUILDING"
    SELL_BUILDING = "SELL_BUILDING"
    MERGE_BUILDING = "MERGE_BUILDING"
    PLACE_BUILDING = "PLACE_BUILDING"
    MOVE_BUILDING = "MOVE_BUILDING"
    UNLOCK_LAND = "UNLOCK_LAND"
    SHOP_REFRESH = "SHOP_REFRESH"
    MANAGEMENT_END = "MANAGEMENT_END"
    PRE_ROLL = "PRE_ROLL"
    ROLL = "ROLL"
    DIE_FACE = "DIE_FACE"
    ROLL_CONDITION = "ROLL_CONDITION"
    AFTER_ROLL = "AFTER_ROLL"
    MOVE_BEGIN = "MOVE_BEGIN"
    PASS_BUILDING = "PASS_BUILDING"
    PASS_START = "PASS_START"
    FORCED_STOP = "FORCED_STOP"
    MOVE_END = "MOVE_END"
    ON_STAY_BUILDING = "ON_STAY_BUILDING"
    LAND_SPECIAL_TILE = "LAND_SPECIAL_TILE"
    TURN_END = "TURN_END"
    STAGE_CLEAR = "STAGE_CLEAR"
    STAND_SELECTION = "STAND_SELECTION"
    GAME_CLEAR = "GAME_CLEAR"
    GAME_OVER = "GAME_OVER"
    GAIN_COIN = "GAIN_COIN"
    SPEND_COIN = "SPEND_COIN"
    GAIN_XP = "GAIN_XP"
    BONUS = "BONUS"
    ADD_BUILDING = "ADD_BUILDING"
    REMOVE_BUILDING = "REMOVE_BUILDING"
    STAND_CHARGE = "STAND_CHARGE"
    SET_FUTURE_DIE = "SET_FUTURE_DIE"


class ActivationCause(StrEnum):
    NATURAL_DIE = "NATURAL_DIE"
    FORCED_DICE_EFFECT = "FORCED_DICE_EFFECT"
    NATURAL_STAY = "NATURAL_STAY"
    TRIGGERED_STAY = "TRIGGERED_STAY"


class TriggerCardinality(StrEnum):
    PER_DIE = "PER_DIE"
    PER_ROLL = "PER_ROLL"


class RuleConfidence(StrEnum):
    VERIFIED_CURRENT = "verified_current"
    COMMUNITY_CURRENT = "community_current"
    CONFIRMED_LEGACY = "confirmed_legacy"
    INFERRED = "inferred"
    UNKNOWN = "unknown"


class SpaceType(StrEnum):
    NORMAL = "NORMAL"
    START = "START"
    COIN = "COIN"
    CARD = "CARD"


class Rarity(StrEnum):
    GREEN = "GREEN"
    BLUE = "BLUE"
    PURPLE = "PURPLE"
    GOLD = "GOLD"
